services:
  - type: web
    name: keycloak-cinthia
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin
    ports:
      - port: 8080
        protocol: http
